### ISSUE TITLE
Error: Could not find schema for: #/definitions/location

### ISSUE THREAD

**Issue by netbe** [clark800/json-schema-to-markdown#1]
Hi, I've got the following error:

```
Users/netbe/.npm-packages/lib/node_modules/json-schema-to-markdown-table/index.js:168
      throw new Error('Could not find schema for: ' + schema.$ref);
      ^

Error: Could not find schema for: #/definitions/location
    at completeSchema (/Users/netbe/.npm-packages/lib/node_modules/json-schema-to-markdown-table/index.js:168:13)
    at generateRowsForSchema (/Users/netbe/.npm-packages/lib/node_modules/json-schema-to-markdown-table/index.js:176:27)
    at /Users/netbe/.npm-packages/lib/node_modules/json-schema-to-markdown-table/index.js:75:12
    at Array.map (native)
    at generateRowsForObject (/Users/netbe/.npm-packages/lib/node_modules/json-schema-to-markdown-table/index.js:73:29)
    at generateRowsForCompleteSchema (/Users/netbe/.npm-packages/lib/node_modules/json-schema-to-markdown-table/index.js:138:12)
    at generateRowsForSchema (/Users/netbe/.npm-packages/lib/node_modules/json-schema-to-markdown-table/index.js:177:10)
    at generateRowsForArray (/Users/netbe/.npm-packages/lib/node_modules/json-schema-to-markdown-table/index.js:84:16)
    at generateRowsForCompleteSchema (/Users/netbe/.npm-packages/lib/node_modules/json-schema-to-markdown-table/index.js:133:14)
    at generateRowsForSchema (/Users/netbe/.npm-packages/lib/node_modules/json-schema-to-markdown-table/index.js:177:10)
```

See `json-schema`:

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Problem",
  "description": "A problem to be solved by the 3RedM API.",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Unique identifier of problem."
    },
    "state": {
      "type": "string",
      "description": "State of the problem.",
      "default": "NEW",
      "enum": [
        "NEW",
        "SOLVED"
      ]
    },
    "solutionId": {
      "type": "string",
      "minLength": 1,
      "title": "SolutionId schema.",
      "description": "Unique identifier of related solution. "
    },
    "description": {
      "type": "string",
      "minLength": 1,
      "title": "Description schema.",
      "default": ""
    },
    "data": {
      "type": "object",
      "title": "Data schema.",
      "description": "An explanation about the purpose of this instance described by this schema.",
      "properties": {
        "jobs": {
          "type": "array",
          "description": "An explanation about the purpose of this instance described by this schema.",
          "name": "jobs",
          "items": {
            "title": "job",
            "type": "object",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "properties": {
              "id": {
                "type": "string"
              },
              "slas": {
                "type": "array",
                "items": {
                  "type": "object",
                  "title": "Service Level Agreement. Supposed delay of job.",
                  "minLength": 1,
                  "maxLength": 5,
                  "properties": {
                    "startTime": {
                      "$ref": "#/definitions/date",
                      "description": "date of beginning of SLA"
                    },
                    "endTime": {
                      "$ref": "#/definitions/date",
                      "description": "date of end of SLA"
                    },
                    "startValue": {
                      "type": "number",
                      "description": "variation of importance of activity in time (can decrease or increase).",
                      "minimum": 0
                    },
                    "endValue": {
                      "type": "number",
                      "description": "variation of importance of activity in time (can decrease or increase)",
                      "minimum": 0
                    }
                  },
                  "required": [
                    "startTime",
                    "endTime",
                    "startValue",
                    "endValue"
                  ]
                }
              },
              "location": {
                "type": "object",
                "$ref": "#/definitions/location"
              },
              "value": {
                "type": "number",
                "description": "value of the activity"
              },
              "skills": {
                "$ref": "#/definitions/skills"
              },
              "duration_s": {
                "type": "integer"
              },
              "resourceId": {
                "type": "string"
              },
              "datetime": {
                "type": "string",
                "format": "date-time"
              },
              "parts": {
                "$ref": "#/definitions/parts"
              },
              "region": {
                "type": "string",
                "description": "region of skills or locations assigned to a resource"
              }
            },
            "required": [
              "id",
              "slas",
              "value",
              "duration_s",
          "location"
            ]
          }
        },
        "resources": {
          "type": "array",
          "title": "Resources schema.",
          "description": "An explanation about the purpose of this instance described by this schema.",
          "name": "resources",
          "minLength": 1,
          "items": {
            "title": "Resource",
            "type": "object",
            "properties": {
              "id": {
                "type": "string"
              },
              "firstName": {
                "type": "string"
              },
              "lastName": {
                "type": "string"
              },
              "skills": {
                "$ref": "#/definitions/skills"
              },
              "parts": {
                "$ref": "#/definitions/parts"
              },
              "startLocation": {
                "type": "object",
                "$ref": "#/definitions/location"
              },
              "endLocation": {
                "type": "object",
                "$ref": "#/definitions/location"
              },
              "shifts": {
                "type": "array",
                "minLength": 1,
                "items": {
                  "type": "object",
                  "properties": {
                    "startTime": {
                      "$ref": "#/definitions/date",
                      "description": "date when the shift starts"
                    },
                    "endTime": {
                      "$ref": "#/definitions/date",
                      "description": "date when the shift ends"
                    }
                  },
                  "requiered": [
                    "startTime",
                    "endTime"
                  ]
                }
              },
              "regions": {
                "type": "array",
                "items": {
                  "type": "string",
                  "description": "region of skills or locations assigned to a resource"
                }
              }
            },
            "required": [
              "id",
              "startLocation",
              "shifts"
            ]
          }
        }
      },
      "required": [
        "resources",
        "jobs"
      ]
    }
  },
  "required": [
    "data",
    "id"
  ],
  "definitions": {
    "skills": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "id of skill"
      }
    },
    "date": {
      "type": "string",
      "description": "ISO 8601 date format",
      "format": "date-time"
    },
    "location": {
      "type": "object",
      "properties": {
        "latitude": {
          "type": "number"
        },
        "longitude": {
          "type": "number"
        },
        "zipCode": {
          "type": "string"
        },
        "address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        }
      },
      "required": [
        "latitude",
        "longitude"
      ]
    },
    "parts": {
      "type": "array",
      "description": "array of part",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "matching identifier of part in resource"
          },
          "value": {
            "type": "integer"
          }
        }
      }
    }
  }
}
```

**Comment by clark800** [comment]
You would have to pass in a second argument for the schemas directory and have a schema in that directory with an `id` of `#/definitions/location`.
